
resources:
    default:
        partition: prod
        account: proj134
        nodes: 2
        time: '12:00:00'
        ntasks_per_node: 1
        mem: 0
        exclusive: true
        constraint: nvme

    sub-tasks:

      # functionalizer 
      - partition: prod
        account: proj134
        nodes: 2
        time: '16:00:00'
        ntasks_per_node: 1
        mem: 0
        exclusive: true
        constraint: nvme

      # parquet to sonata conversion
      - partition: prod
        nodes: 2
        ntasks_per_node: 10
        cpus_per_task: 4
        exclusive: true
        time: '8:00:00'
        mem: 0
        account: proj134
