
resources:
    default:
        partition: prod
        account: proj134
        nodes: 20
        time: '12:00:00'
        ntasks_per_node: 1
        mem: 0
        exclusive: true
        constraint: nvme
