
resources:
    region:
        default: 
            salloc: -A ${{SALLOC_ACCOUNT}} -p prod_small -C cpu -n 1 --time 1:00:00 --exclusive
            jobname: ${{TASK_NAME}}
            env_vars:
                SALLOC_ACCOUNT: ${{SALLOC_ACCOUNT}}
                https_proxy: http://bbpproxy.epfl.ch:80/
        root:
            salloc: -A ${{SALLOC_ACCOUNT}} -p prod -C cpu -n 1 --time 2:00:00 --exclusive
            jobname: ${{TASK_NAME}}
            env_vars:
                SALLOC_ACCOUNT: ${{SALLOC_ACCOUNT}}
                https_proxy: http://bbpproxy.epfl.ch:80/
