
resources:
    default:
        partition: prod
        account: proj134
        exclusive: true
        time: '12:00:00'
        ntasks: 720
        mem: 0
        constraint: nvme

    sub-tasks:

      # emodel-generalisation assign
      - partition: prod
        account: proj134
        exclusive: true
        time: '1:00:00'
        nodes: 1
        mem: 0

      # emodel-generalisation adapt
      - partition: prod
        account: proj134
        exclusive: true
        time: '11:00:00'
        constraint: nvme
        ntasks: 720
        mem: 0

      # emodel-generalisation currents
      - partition: prod
        account: proj134
        exclusive: true
        time: '12:00:00'
        constraint: nvme
        ntasks: 720
        mem: 0
