
resources:
    default:
        partition: prod
        nodes: 300
        tasks_per_node: 1
        cpus_per_task: 40
        exclusive: true
        time: '1-00:00:00'
        mem: 0
        account: proj134
